version: "3.7"

services: 
    db:
        image: postgres:13
        container_name: postgres
        volumes:
          - ./data/db:/var/lib/postgresql/data
        environment:
          - POSTGRES_DB=postgres
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports: 
        - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
    api:
        container_name: api
        build:
            context: api-src/
            dockerfile: Dockerfile 
        volumes:
            - ./api-src:/api
        ports:
            - "8000:8000"
        depends_on:
            - db
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    web:
        container_name: react
        build:
            context: react/
            dockerfile: Dockerfile
        volumes: 
            - ./react:/app
        ports:
            - "3000:3000"
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: ["yarn", "start"]