# Generated by Django 3.2.2 on 2021-06-08 22:40

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BioDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('document', models.FileField(blank=True, null=True, upload_to=documents.models.AbstractBioDocument.document_upload_location)),
            ],
            options={
                'verbose_name': 'Document',
            },
        ),
        migrations.CreateModel(
            name='BioDocumentAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('document', models.ImageField(blank=True, null=True, upload_to=documents.models.AbstractBioDocument.document_upload_location)),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audio Files',
            },
        ),
        migrations.CreateModel(
            name='BioDocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('document', models.ImageField(blank=True, null=True, upload_to=documents.models.AbstractBioDocument.document_upload_location)),
            ],
            options={
                'verbose_name': 'Image',
            },
        ),
        migrations.CreateModel(
            name='BioDocumentVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=250)),
                ('document', models.ImageField(blank=True, null=True, upload_to=documents.models.AbstractBioDocument.document_upload_location)),
            ],
            options={
                'verbose_name': 'Video',
            },
        ),
    ]
