# Generated by Django 3.2.2 on 2021-06-08 22:49

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodocumentaudio',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.AbstractBioDocument.document_upload_location),
        ),
        migrations.AlterField(
            model_name='biodocumentvideo',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.AbstractBioDocument.document_upload_location),
        ),
    ]
