# Generated by Django 3.2.2 on 2021-06-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(default='', max_length=250)),
                ('name_last', models.CharField(default='', max_length=250)),
                ('date_birth', models.DateTimeField(null=True)),
                ('date_death', models.DateTimeField(null=True)),
                ('location_birth', models.CharField(default='', max_length=250)),
                ('location_death', models.CharField(default='', max_length=250)),
            ],
        ),
    ]
