# Generated by Django 3.2.2 on 2021-06-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_death',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='location_birth',
            field=models.CharField(blank=True, default='', max_length=2250, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='location_death',
            field=models.CharField(blank=True, default='', max_length=2250, null=True),
        ),
    ]
