# Generated by Django 3.2.2 on 2021-06-08 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20210608_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membercategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='member',
            name='member_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='members.membercategory'),
        ),
    ]
